name: dayrepair
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_screenutil: ^0.6.1
  flutter_swiper: ^1.1.6
  dio: ">=3.0.5 <6.0.0"
  date_format: ^1.0.8
  device_info: ^0.4.1+1
  provider: ^3.2.0
  shared_preferences: ^0.5.4+8
  event_bus: ^1.1.0
  fluttertoast: ^3.1.3
  flutter_easyrefresh: ^2.0.8
  amap_location: ^0.2.0
  flui: ^0.7.4
  flustars: ^0.2.6+1
  url_launcher: ^5.2.5
  flutter_inappwebview: ^2.1.0+1
  # address_picker: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - images/home_tab.png
   - images/2.0x/home_tab.png
   - images/3.0x/home_tab.png
   - images/home_select_tab.png
   - images/2.0x/home_select_tab.png
   - images/3.0x/home_select_tab.png
   - images/mall_tab.png
   - images/2.0x/mall_tab.png
   - images/3.0x/mall_tab.png
   - images/mall_select_tab.png
   - images/2.0x/mall_select_tab.png
   - images/3.0x/mall_select_tab.png
   - images/join_tab.png
   - images/2.0x/join_tab.png
   - images/3.0x/join_tab.png
   - images/join_select_tab.png
   - images/2.0x/join_select_tab.png
   - images/3.0x/join_select_tab.png
   - images/my_tab.png
   - images/2.0x/my_tab.png
   - images/3.0x/my_tab.png
   - images/my_select_tab.png
   - images/2.0x/my_select_tab.png
   - images/3.0x/my_select_tab.png
   - images/join_tc.png
   - images/2.0x/join_tc.png
   - images/3.0x/join_tc.png
   - images/zxxd.png
   - images/2.0x/zxxd.png
   - images/3.0x/zxxd.png
   - images/kfdl.png
   - images/2.0x/kfdl.png
   - images/3.0x/kfdl.png
   - images/gcssm.png
   - images/2.0x/gcssm.png
   - images/3.0x/gcssm.png
   - images/wczf.png
   - images/2.0x/wczf.png
   - images/3.0x/wczf.png
   - images/rspj.png
   - images/2.0x/rspj.png
   - images/3.0x/rspj.png
   - images/drx_pmsp.png
   - images/2.0x/drx_pmsp.png
   - images/3.0x/drx_pmsp.png
   - images/drx_smallLogon.png
   - images/2.0x/drx_smallLogon.png
   - images/3.0x/drx_smallLogon.png
   - images/join_dp.png
   - images/2.0x/join_dp.png
   - images/3.0x/join_dp.png
   - images/join_gcsjm.png
   - images/2.0x/join_gcsjm.png
   - images/3.0x/join_gcsjm.png
   - images/drx_no_login.png
   - images/2.0x/drx_no_login.png
   - images/3.0x/drx_no_login.png
   - images/my_wxdd.png
   - images/2.0x/my_wxdd.png
   - images/3.0x/my_wxdd.png
   - images/my_yhj.png
   - images/2.0x/my_yhj.png
   - images/3.0x/my_yhj.png
   - images/my_fwdz.png
   - images/2.0x/my_fwdz.png
   - images/3.0x/my_fwdz.png
   - images/my_order.png
   - images/2.0x/my_order.png
   - images/3.0x/my_order.png
   - images/drx_logon.png
   - images/2.0x/drx_logon.png
   - images/3.0x/drx_logon.png
   - images/WxLogin.png
   - images/2.0x/WxLogin.png
   - images/3.0x/WxLogin.png
   - images/drx_couponN.png
   - images/2.0x/drx_couponN.png
   - images/3.0x/drx_couponN.png
   - images/drx_couponY.png
   - images/2.0x/drx_couponY.png
   - images/3.0x/drx_couponY.png
   - images/n_order.png
   - images/2.0x/n_order.png
   - images/3.0x/n_order.png
   - data/WxOrderType.json
   - data/WxOrderStatus.json
   - data/CommodityDetails.js
   - lib/thirdLibrary/address_picker/address.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: SourceHanSansCNRegular
      fonts:
        - asset: fonts/SourceHanSansCN-Regular.otf
    - family: SourceHanSansCNBold
      fonts:
        - asset: fonts/SourceHanSansCN-Bold.otf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
