///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class SpecGoodsPriceModel {
/*
{
  "item_id": "336",
  "goods_id": "333",
  "key": "245",
  "key_name": "颜色:中国红",
  "price": "88.00",
  "store_count": "100",
  "bar_code": "",
  "sku": "",
  "spec_img": "http://img.dangrixiu.cn/ab41e13582a3f10fdbe3f601baf6540620190410103629.png",
  "prom_id": "0",
  "prom_type": "0",
  "recycle_id": "0"
} 
*/

  String itemId;
  String goodsId;
  String key;
  String keyName;
  String price;
  String storeCount;
  String barCode;
  String sku;
  String specImg;
  String promId;
  String promType;
  String recycleId;

  SpecGoodsPriceModel({
    this.itemId,
    this.goodsId,
    this.key,
    this.keyName,
    this.price,
    this.storeCount,
    this.barCode,
    this.sku,
    this.specImg,
    this.promId,
    this.promType,
    this.recycleId,
  });
  SpecGoodsPriceModel.fromJson(Map<String, dynamic> json) {
    itemId = json["item_id"]?.toString();
    goodsId = json["goods_id"]?.toString();
    key = json["key"]?.toString();
    keyName = json["key_name"]?.toString();
    price = json["price"]?.toString();
    storeCount = json["store_count"]?.toString();
    barCode = json["bar_code"]?.toString();
    sku = json["sku"]?.toString();
    specImg = json["spec_img"]?.toString();
    promId = json["prom_id"]?.toString();
    promType = json["prom_type"]?.toString();
    recycleId = json["recycle_id"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["item_id"] = itemId;
    data["goods_id"] = goodsId;
    data["key"] = key;
    data["key_name"] = keyName;
    data["price"] = price;
    data["store_count"] = storeCount;
    data["bar_code"] = barCode;
    data["sku"] = sku;
    data["spec_img"] = specImg;
    data["prom_id"] = promId;
    data["prom_type"] = promType;
    data["recycle_id"] = recycleId;
    return data;
  }
}

class GoodsSpecListModel {
/*
{
  "item_id": "245",
  "item": "中国红",
  "src": "http://img.dangrixiu.cn/ab41e13582a3f10fdbe3f601baf6540620190410103629.png"
} 
*/

  String itemId;
  String item;
  String src;

  GoodsSpecListModel({
    this.itemId,
    this.item,
    this.src,
  });
  GoodsSpecListModel.fromJson(Map<String, dynamic> json) {
    itemId = json["item_id"]?.toString();
    item = json["item"]?.toString();
    src = json["src"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["item_id"] = itemId;
    data["item"] = item;
    data["src"] = src;
    return data;
  }
}

class GoodsSpecModel {
/*
{
  "name": "颜色",
  "list": [
    {
      "item_id": "245",
      "item": "中国红",
      "src": "http://img.dangrixiu.cn/ab41e13582a3f10fdbe3f601baf6540620190410103629.png"
    }
  ]
} 
*/

  String name;
  List<GoodsSpecListModel> list;

  GoodsSpecModel({
    this.name,
    this.list,
  });
  GoodsSpecModel.fromJson(Map<String, dynamic> json) {
    name = json["name"]?.toString();
    if (json["list"] != null) {
      var v = json["list"];
      var arr0 = List<GoodsSpecListModel>();
      v.forEach((v) {
        arr0.add(GoodsSpecListModel.fromJson(v));
      });
      list = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["name"] = name;
    if (list != null) {
      var v = list;
      var arr0 = List();
      v.forEach((v) {
        arr0.add(v.toJson());
      });
      data["list"] = arr0;
    }
    return data;
  }
}

class CommodityDetailsDataModel {
/*
{
  "goods_id": "333",
  "original_img": "http://img.dangrixiu.cn/ad2755f5863046bbce5511590bb81fa020190410102037.png",
  "goods_name": "20000毫安迷你大容量充电宝强光手电筒户外超薄便携小巧适用苹果小米华为手机快充闪充移动电源定制logo刻字",
  "shop_price": "88.00",
  "parent_id_path": "0_3_27",
  "sales_sum": "0",
  "goods_content": "https://wx.dangrixiu.cn/api/Mall/html_content/goods_id/333",
  "cart_count": "0",
  "goods_spec": [
    {
      "name": "颜色",
      "list": [
        {
          "item_id": "245",
          "item": "中国红",
          "src": "http://img.dangrixiu.cn/ab41e13582a3f10fdbe3f601baf6540620190410103629.png"
        }
      ]
    }
  ],
  "price_range": "88.00",
  "spec_goods_price": [
    {
      "item_id": "336",
      "goods_id": "333",
      "key": "245",
      "key_name": "颜色:中国红",
      "price": "88.00",
      "store_count": "100",
      "bar_code": "",
      "sku": "",
      "spec_img": "http://img.dangrixiu.cn/ab41e13582a3f10fdbe3f601baf6540620190410103629.png",
      "prom_id": "0",
      "prom_type": "0",
      "recycle_id": "0"
    }
  ],
  "goods_image_url": [
    "http://img.dangrixiu.cn/30c840436d40d1e65fbe401d7d1e7f3220190410102003.png"
  ]
} 
*/

  String goodsId;
  String originalImg;
  String goodsName;
  String shopPrice;
  String parentIdPath;
  String salesSum;
  String goodsContent;
  String cartCount;
  List<GoodsSpecModel> goodsSpec;
  String priceRange;
  List<SpecGoodsPriceModel> specGoodsPrice;
  List<String> goodsImageUrl;

  CommodityDetailsDataModel({
    this.goodsId,
    this.originalImg,
    this.goodsName,
    this.shopPrice,
    this.parentIdPath,
    this.salesSum,
    this.goodsContent,
    this.cartCount,
    this.goodsSpec,
    this.priceRange,
    this.specGoodsPrice,
    this.goodsImageUrl,
  });
  CommodityDetailsDataModel.fromJson(Map<String, dynamic> json) {
    goodsId = json["goods_id"]?.toString();
    originalImg = json["original_img"]?.toString();
    goodsName = json["goods_name"]?.toString();
    shopPrice = json["shop_price"]?.toString();
    parentIdPath = json["parent_id_path"]?.toString();
    salesSum = json["sales_sum"]?.toString();
    goodsContent = json["goods_content"]?.toString();
    cartCount = json["cart_count"]?.toString();
    if (json["goods_spec"] != null) {
      var v = json["goods_spec"];
      var arr0 = List<GoodsSpecModel>();
      v.forEach((v) {
        arr0.add(GoodsSpecModel.fromJson(v));
      });
      goodsSpec = arr0;
    }
    priceRange = json["price_range"]?.toString();
    if (json["spec_goods_price"] != null) {
      var v = json["spec_goods_price"];
      var arr0 = List<SpecGoodsPriceModel>();
      v.forEach((v) {
        arr0.add(SpecGoodsPriceModel.fromJson(v));
      });
      specGoodsPrice = arr0;
    }
    if (json["goods_image_url"] != null) {
      var v = json["goods_image_url"];
      var arr0 = List<String>();
      v.forEach((v) {
        arr0.add(v.toString());
      });
      goodsImageUrl = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["goods_id"] = goodsId;
    data["original_img"] = originalImg;
    data["goods_name"] = goodsName;
    data["shop_price"] = shopPrice;
    data["parent_id_path"] = parentIdPath;
    data["sales_sum"] = salesSum;
    data["goods_content"] = goodsContent;
    data["cart_count"] = cartCount;
    if (goodsSpec != null) {
      var v = goodsSpec;
      var arr0 = List();
      v.forEach((v) {
        arr0.add(v.toJson());
      });
      data["goods_spec"] = arr0;
    }
    data["price_range"] = priceRange;
    if (specGoodsPrice != null) {
      var v = specGoodsPrice;
      var arr0 = List();
      v.forEach((v) {
        arr0.add(v.toJson());
      });
      data["spec_goods_price"] = arr0;
    }
    if (goodsImageUrl != null) {
      var v = goodsImageUrl;
      var arr0 = List();
      v.forEach((v) {
        arr0.add(v);
      });
      data["goods_image_url"] = arr0;
    }
    return data;
  }
}

class CommodityDetailsModel {
/*
{
  "status": 1,
  "msg": "成功",
  "data": {
    "goods_id": "333",
    "original_img": "http://img.dangrixiu.cn/ad2755f5863046bbce5511590bb81fa020190410102037.png",
    "goods_name": "20000毫安迷你大容量充电宝强光手电筒户外超薄便携小巧适用苹果小米华为手机快充闪充移动电源定制logo刻字",
    "shop_price": "88.00",
    "parent_id_path": "0_3_27",
    "sales_sum": "0",
    "goods_content": "https://wx.dangrixiu.cn/api/Mall/html_content/goods_id/333",
    "cart_count": "0",
    "goods_spec": [
      {
        "name": "颜色",
        "list": [
          {
            "item_id": "245",
            "item": "中国红",
            "src": "http://img.dangrixiu.cn/ab41e13582a3f10fdbe3f601baf6540620190410103629.png"
          }
        ]
      }
    ],
    "price_range": "88.00",
    "spec_goods_price": [
      {
        "item_id": "336",
        "goods_id": "333",
        "key": "245",
        "key_name": "颜色:中国红",
        "price": "88.00",
        "store_count": "100",
        "bar_code": "",
        "sku": "",
        "spec_img": "http://img.dangrixiu.cn/ab41e13582a3f10fdbe3f601baf6540620190410103629.png",
        "prom_id": "0",
        "prom_type": "0",
        "recycle_id": "0"
      }
    ],
    "goods_image_url": [
      "http://img.dangrixiu.cn/30c840436d40d1e65fbe401d7d1e7f3220190410102003.png"
    ]
  }
} 
*/

  int status;
  String msg;
  CommodityDetailsDataModel data;

  CommodityDetailsModel({
    this.status,
    this.msg,
    this.data,
  });
  CommodityDetailsModel.fromJson(Map<String, dynamic> json) {
    status = json["status"]?.toInt();
    msg = json["msg"]?.toString();
    data =
        json["data"] != null ? CommodityDetailsDataModel.fromJson(json["data"]) : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["status"] = status;
    data["msg"] = msg;
    if (data != null) {
      data["data"] = this.data.toJson();
    }
    return data;
  }
}
