import 'dart:convert';

import 'package:flutter/foundation.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class Evaluate {
  String image;
  String name;
  String cat;
  String fault;
  String time;
  String evaluate;
  String star;

  Evaluate({
    this.image,
    this.name,
    this.cat,
    this.fault,
    this.time,
    this.evaluate,
    this.star,
  });
  Evaluate.fromJson(Map<String, dynamic> json) {
    image = json["image"]?.toString();
    name = json["name"]?.toString();
    cat = json["cat"]?.toString();
    fault = json["fault"]?.toString();
    time = json["time"]?.toString();
    evaluate = json["evaluate"]?.toString();
    star = json["star"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["image"] = image;
    data["name"] = name;
    data["cat"] = cat;
    data["fault"] = fault;
    data["time"] = time;
    data["evaluate"] = evaluate;
    data["star"] = star;
    return data;
  }
}

class VersionInfo {
/*
{
  "title": "当日修更新啦！",
  "desc": "检测到新版本v1.2.1",
  "version": "v1.2.1",
  "version_num": "3",
  "is_update": "0",
  "min_version_num": "1",
  "function": [
    "解决现有系统bug"
  ],
  "url": "http://img.dangrixiu.cn/drx1553757346.apk"
} 
*/

  String title;
  String desc;
  String version;
  String versionNum;
  String isUpdate;
  String minVersionNum;
  List<String> function;
  String url;

  VersionInfo({
    this.title,
    this.desc,
    this.version,
    this.versionNum,
    this.isUpdate,
    this.minVersionNum,
    this.function,
    this.url,
  });
  VersionInfo.fromJson(Map<String, dynamic> json) {
    title = json["title"]?.toString();
    desc = json["desc"]?.toString();
    version = json["version"]?.toString();
    versionNum = json["version_num"]?.toString();
    isUpdate = json["is_update"]?.toString();
    minVersionNum = json["min_version_num"]?.toString();
    if (json["function"] != null) {
      var v = json["function"];
      var arr0 = List<String>();
      v.forEach((v) {
      arr0.add(v.toString());
      });
        function = arr0;
    }
    url = json["url"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["title"] = title;
    data["desc"] = desc;
    data["version"] = version;
    data["version_num"] = versionNum;
    data["is_update"] = isUpdate;
    data["min_version_num"] = minVersionNum;
    if (function != null) {
      var v = function;
      var arr0 = List();
  v.forEach((v) {
  arr0.add(v);
  });
      data["function"] = arr0;
    }
    data["url"] = url;
    return data;
  }
}

class CouponList {
  String id;
  String name;
  String couponType;
  String type;
  String money;
  String condition;
  String getUpLimit;
  String createnum;
  String sendNum;
  String useNum;
  String sendStartTime;
  String sendEndTime;
  String useStartTime;
  String useEndTime;
  String addTime;
  String modifyTime;
  String status;
  String useType;

  CouponList({
    this.id,
    this.name,
    this.couponType,
    this.type,
    this.money,
    this.condition,
    this.getUpLimit,
    this.createnum,
    this.sendNum,
    this.useNum,
    this.sendStartTime,
    this.sendEndTime,
    this.useStartTime,
    this.useEndTime,
    this.addTime,
    this.modifyTime,
    this.status,
    this.useType,
  });
  CouponList.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toString();
    name = json["name"]?.toString();
    couponType = json["coupon_type"]?.toString();
    type = json["type"]?.toString();
    money = json["money"]?.toString();
    condition = json["condition"]?.toString();
    getUpLimit = json["get_up_limit"]?.toString();
    createnum = json["createnum"]?.toString();
    sendNum = json["send_num"]?.toString();
    useNum = json["use_num"]?.toString();
    sendStartTime = json["send_start_time"]?.toString();
    sendEndTime = json["send_end_time"]?.toString();
    useStartTime = json["use_start_time"]?.toString();
    useEndTime = json["use_end_time"]?.toString();
    addTime = json["add_time"]?.toString();
    modifyTime = json["modify_time"]?.toString();
    status = json["status"]?.toString();
    useType = json["use_type"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["name"] = name;
    data["coupon_type"] = couponType;
    data["type"] = type;
    data["money"] = money;
    data["condition"] = condition;
    data["get_up_limit"] = getUpLimit;
    data["createnum"] = createnum;
    data["send_num"] = sendNum;
    data["use_num"] = useNum;
    data["send_start_time"] = sendStartTime;
    data["send_end_time"] = sendEndTime;
    data["use_start_time"] = useStartTime;
    data["use_end_time"] = useEndTime;
    data["add_time"] = addTime;
    data["modify_time"] = modifyTime;
    data["status"] = status;
    data["use_type"] = useType;
    return data;
  }
}

class Banner {
  String adCode;
  String adLink;
  String mediaType;

  Banner({
    this.adCode,
    this.adLink,
    this.mediaType,
  });
  Banner.fromJson(Map<String, dynamic> json) {
    adCode = json["ad_code"]?.toString();
    adLink = json["ad_link"]?.toString();
    mediaType = json["media_type"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["ad_code"] = adCode;
    data["ad_link"] = adLink;
    data["media_type"] = mediaType;
    return data;
  }
}

class HotRepair {
  String phoneId;
  int price;
  String faultId;
  String phoneName;
  String faultName;
  String img;

  HotRepair({
    this.phoneId,
    this.price,
    this.faultId,
    this.phoneName,
    this.faultName,
    this.img,
  });
  HotRepair.fromJson(Map<String, dynamic> json) {
    phoneId = json["phone_id"]?.toString();
    price = json["price"]?.toInt();
    faultId = json["fault_id"]?.toString();
    phoneName = json["phone_name"]?.toString();
    faultName = json["fault_name"]?.toString();
    img = json["img"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["phone_id"] = phoneId;
    data["price"] = price;
    data["fault_id"] = faultId;
    data["phone_name"] = phoneName;
    data["fault_name"] = faultName;
    data["img"] = img;
    return data;
  }
}

class HomeDataItemModel {
  String replaceBatteryImg;
  String replaceScreenImg;
  String isReview;
  List<List<HotRepair>> hotRepair;
  List<Banner> banner;
  String bottomImg;
  String phoneId;
  String phoneName;
  String isUpdate;
  String couponShow;
  List<CouponList> couponList;
  VersionInfo versionInfo;
  List<Evaluate> evaluate;

  HomeDataItemModel({
    this.replaceBatteryImg,
    this.replaceScreenImg,
    this.isReview,
    this.hotRepair,
    this.banner,
    this.bottomImg,
    this.phoneId,
    this.phoneName,
    this.isUpdate,
    this.couponShow,
    this.couponList,
    this.versionInfo,
    this.evaluate,
  });
  HomeDataItemModel.fromJson(Map<String, dynamic> jsons) {
    replaceBatteryImg = jsons["replace_battery_img"]?.toString();
    replaceScreenImg = jsons["replace_screen_img"]?.toString();
    isReview = jsons["is_review"]?.toString();
  if (jsons["hot_repair"] != null) {
    var v = jsons["hot_repair"];
    var arr0 = List<List<HotRepair>>();
      v.forEach((v) {
        var arr1 = List<HotRepair>();
        v.forEach((v) {
          arr1.add(HotRepair.fromJson(v));
        });
        arr0.add(arr1);
      });
      hotRepair = arr0;
    }
  if (jsons["banner"] != null) {
      var v = jsons["banner"];
      var arr0 = List<Banner>();
      v.forEach((v) {
      arr0.add(Banner.fromJson(v));
      });
      banner = arr0;
    }
    bottomImg = jsons["bottom_img"]?.toString();
    phoneId = jsons["phone_id"]?.toString();
    phoneName = jsons["phone_name"]?.toString();
    isUpdate = jsons["is_update"]?.toString();
    couponShow = jsons["coupon_show"]?.toString();
  if (jsons["coupon_list"] != null) {
      var v = jsons["coupon_list"];
      var arr0 = List<CouponList>();
      v.forEach((v) {
      arr0.add(CouponList.fromJson(v));
      });
        couponList = arr0;
    }
    
    // print("=====${jsons["version_info"]}");
    if(jsons["version_info"] != null && jsons["version_info"] != ""){
      versionInfo = VersionInfo.fromJson(jsons["version_info"]);
    }else{
      versionInfo = null;
    }
    // versionInfo = jsons["version_info"] != null ? SomeRootEntityDataVersionInfo.fromJson(jsons["version_info"]) : null;
  if (jsons["evaluate"] != null) {
    var v = jsons["evaluate"];
    var arr0 = List<Evaluate>();
    v.forEach((v) {
    arr0.add(Evaluate.fromJson(v));
    });
      evaluate = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["replace_battery_img"] = replaceBatteryImg;
    data["replace_screen_img"] = replaceScreenImg;
    data["is_review"] = isReview;
    if (hotRepair != null) {
      var v = hotRepair;
      var arr0 = List();
      v.forEach((v) {
        var arr1 = List();
        v.forEach((v) {
          arr1.add(v.toJson());
        });
        arr0.add(arr1);
      });
      data["hot_repair"] = arr0;
    }
    if (banner != null) {
      var v = banner;
      var arr0 = List();
  v.forEach((v) {
  arr0.add(v.toJson());
  });
      data["banner"] = arr0;
    }
    data["bottom_img"] = bottomImg;
    data["phone_id"] = phoneId;
    data["phone_name"] = phoneName;
    data["is_update"] = isUpdate;
    data["coupon_show"] = couponShow;
    if (couponList != null) {
      var v = couponList;
      var arr0 = List();
  v.forEach((v) {
  arr0.add(v.toJson());
  });
      data["coupon_list"] = arr0;
    }
    if (versionInfo != null) {
      data["version_info"] = versionInfo.toJson();
    }
    if (evaluate != null) {
      var v = evaluate;
      var arr0 = List();
  v.forEach((v) {
  arr0.add(v.toJson());
  });
      data["evaluate"] = arr0;
    }
    return data;
  }
}


class HomeDataModel {
  int status;
  String msg;
  HomeDataItemModel data;

  HomeDataModel({
    this.status,
    this.msg,
    this.data,
  });
  HomeDataModel.fromJson(Map<String, dynamic> json) {

    status = json["status"]?.toInt();
    msg = json["msg"]?.toString();
    data = json["data"] != null ? HomeDataItemModel.fromJson(json["data"]) : null;

    // return HomeDataModel(
    //   status:json["status"]?.toInt(),
    //   msg:json["msg"]?.toString(),
    //   data:json["data"] != null ? HomeDataItemModel.fromJson(json["data"]) : null,
    // );
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["status"] = status;
    data["msg"] = msg;
    if (data != null) {
      data["data"] = this.data.toJson();
    }
    return data;
  }
}

